name: "Cura-plugin release"

on:
  push:
    tags:
      - "v*"

jobs:
  create-curapackages:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: "repo"
          submodules: "recursive"
      - name: Create folder for files which are part of plugin
        run: mkdir -p build
      - name: Copy files needed for the build
        working-directory: repo
        run: |
          cp __init__.py ../build/
          cp html_end.html ../build/
          cp html_main_start.html ../build/
          cp html_start.html ../build/
          cp html_sticky_compare.html ../build/
          cp html_sticky_report.html ../build/
          cp HTMLSettingsExportReborn.py ../build/
          cp LICENSE ../build/
          cp plugin.json ../build/
          cp README.md ../build/
      - uses: fieldOfView/cura-plugin-packager-action@main
        with:
          source_folder: "build"
          package_info_path: "repo/.github/workflows/package.json"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.curapackage
